version: '3'
services:
  backend_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: '${APP_NAME}-backend'
    restart: always
    depends_on:
      - db
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8003:8000"
    volumes:
      - ./:/usr/src/app
  db:
    image: postgres:14.3
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: '${APP_NAME}-db'
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    external: false